#!/usr/bin/env python3
"""
Distribution Engine — deploys insight pages to GitHub Pages or Cloudflare Worker.

Reads generated HTML from data/pages/ and deploys to:
  - GitHub Pages: https://bookchaowalit.github.io/solo-empire-insights/
  - Cloudflare Worker: https://solo-empire-insights.workers.dev

Usage:
    python3 domains/product/engineering/book-dev/book-scraping/scripts/publish_pages.py
    python3 domains/product/engineering/book-dev/book-scraping/scripts/publish_pages.py --target github
    python3 domains/product/engineering/book-dev/book-scraping/scripts/publish_pages.py --target cloudflare
    python3 domains/product/engineering/book-dev/book-scraping/scripts/publish_pages.py --dry-run
    python3 domains/product/engineering/book-dev/book-scraping/scripts/publish_pages.py --generate-only
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

try:
    from dotenv import load_dotenv
    _root = Path(__file__).resolve().parents[4]
    load_dotenv(_root / ".env")
except ImportError:
    pass

ROOT = Path(__file__).resolve().parents[4]
PAGES_DIR = ROOT / "data" / "pages"
WORKER_DIR = ROOT / "data" / "insights-worker"
DEFAULT_WORKER_NAME = "solo-empire-insights"
GITHUB_REPO = "bookchaowalit/solo-empire-insights"
GITHUB_PAGES_URL = f"https://{GITHUB_REPO.split('/')[0]}.github.io/{GITHUB_REPO.split('/')[1]}/"


def load_cloudflare_env():
    """Load Cloudflare credentials from .env."""
    env_path = ROOT / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    key = key.strip()
                    val = val.strip()
                    if key not in os.environ:
                        os.environ[key] = val

    account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "")
    api_token = os.environ.get("CLOUDFLARE_API_TOKEN", "")
    return account_id, api_token


def generate_worker_script(pages: dict) -> str:
    """Generate a Cloudflare Worker script that serves all insight pages."""
    pages_json = json.dumps(pages, ensure_ascii=False)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f"""// Solo Empire Insights Worker
// Auto-generated by publish_pages.py — do not edit manually
// Deployed: {now}

const PAGES = {pages_json};

const ROUTES = {{
  "/": "index.html",
  "/index": "index.html",
  "/index.html": "index.html",
  "/crypto": "crypto.html",
  "/exchange_rates": "exchange_rates.html",
  "/stocks": "stocks.html",
  "/defi": "defi.html",
  "/github_trending": "github_trending.html",
  "/jobs": "jobs.html",
  "/flights": "flights.html",
  "/opportunities": "opportunities.html",
  "/property": "property.html",
  "/seo": "seo.html",
  "/ai_tools": "ai_tools.html",
}};

export default {{
  async fetch(request) {{
    const url = new URL(request.url);
    let path = url.pathname.replace(/\\/$/, "") || "/";

    const file = ROUTES[path];
    if (!file || !PAGES[file]) {{
      return new Response(PAGES["index.html"], {{
        headers: {{ "Content-Type": "text/html; charset=utf-8" }},
      }});
    }}

    return new Response(PAGES[file], {{
      headers: {{
        "Content-Type": "text/html; charset=utf-8",
        "X-Powered-By": "Solo Empire Insights Engine",
        "Cache-Control": "public, max-age=3600",
      }},
    }});
  }},
}};
"""


def prepare_pages() -> dict:
    """Read all HTML pages and return as {filename: content} dict."""
    if not PAGES_DIR.exists():
        print(f"ERROR: {PAGES_DIR} not found. Run generate_pages.py first.")
        sys.exit(1)

    html_files = list(PAGES_DIR.glob("*.html"))
    if not html_files:
        print(f"ERROR: No HTML files in {PAGES_DIR}. Run generate_pages.py first.")
        sys.exit(1)

    pages = {}
    for f in sorted(html_files):
        pages[f.name] = f.read_text(encoding="utf-8")
        print(f"    - {f.name} ({f.stat().st_size / 1024:.1f} KB)")

    return pages


def generate_only(worker_name: str) -> str:
    """Generate the worker script and save to disk. Returns the script path."""
    print(f"  Reading pages...")
    pages = prepare_pages()

    total_size = sum(len(v) for v in pages.values())
    print(f"  Total: {len(pages)} pages ({total_size / 1024:.1f} KB)")

    worker_script = generate_worker_script(pages)

    WORKER_DIR.mkdir(parents=True, exist_ok=True)
    script_path = WORKER_DIR / "worker.js"
    script_path.write_text(worker_script, encoding="utf-8")
    print(f"\n  Worker script: {script_path} ({len(worker_script) / 1024:.1f} KB)")

    return str(script_path)


def deploy_via_wrangler(worker_name: str) -> bool:
    """Deploy the worker via wrangler."""
    account_id, api_token = load_cloudflare_env()
    if not account_id or not api_token:
        print("  ERROR: Missing CLOUDFLARE_ACCOUNT_ID or CLOUDFLARE_API_TOKEN")
        return False

    script_path = generate_only(worker_name)

    env = os.environ.copy()
    env["CLOUDFLARE_API_TOKEN"] = api_token
    env["CLOUDFLARE_ACCOUNT_ID"] = account_id

    cmd = [
        "npx", "wrangler", "deploy",
        str(script_path),
        "--name", worker_name,
        "--compatibility-date", "2024-01-01",
    ]

    print(f"\n  Deploying worker '{worker_name}' via wrangler...")
    result = subprocess.run(
        cmd, capture_output=True, text=True, env=env, cwd=str(ROOT), timeout=120
    )

    if result.returncode == 0:
        print(f"\n  Deployed successfully!")
        print(f"  Live at: https://{worker_name}.workers.dev")
        for line in result.stdout.strip().split("\n")[-5:]:
            if line.strip():
                print(f"    {line.strip()}")
        return True
    else:
        err = result.stderr[-500:] if result.stderr else result.stdout[-500:]
        print(f"\n  Deploy failed: {err}")
        return False


def deploy_to_github(dry_run: bool = False) -> bool:
    """Deploy insight pages to GitHub Pages via git push."""
    pages = prepare_pages()
    total_size = sum(len(v) for v in pages.values())
    print(f"  Total: {len(pages)} pages ({total_size / 1024:.1f} KB)")

    if dry_run:
        print(f"  [DRY RUN] Would push {len(pages)} pages to {GITHUB_REPO}")
        print(f"  Target: {GITHUB_PAGES_URL}")
        return True

    repo_url = f"https://github.com/{GITHUB_REPO}.git"
    tmp_dir = ROOT / ".tmp-insights-deploy"

    try:
        # Clone the target repo
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)

        print(f"\n  Cloning {GITHUB_REPO}...")
        result = subprocess.run(
            ["git", "clone", repo_url, str(tmp_dir)],
            capture_output=True, text=True, timeout=60
        )
        if result.returncode != 0:
            print(f"  ERROR: Clone failed: {result.stderr[-300:]}")
            return False

        # Copy HTML files
        for f in PAGES_DIR.glob("*.html"):
            shutil.copy2(f, tmp_dir / f.name)

        # Check for changes
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, cwd=str(tmp_dir)
        )
        if not result.stdout.strip():
            print("  No changes detected — pages are up to date.")
            return True

        # Commit and push
        subprocess.run(["git", "add", "-A"], cwd=str(tmp_dir), check=True)

        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        env = os.environ.copy()
        env.setdefault("GIT_AUTHOR_NAME", "bookchaowalit")
        env.setdefault("GIT_AUTHOR_EMAIL", "bookchaowalit@users.noreply.github.com")
        env.setdefault("GIT_COMMITTER_NAME", "bookchaowalit")
        env.setdefault("GIT_COMMITTER_EMAIL", "bookchaowalit@users.noreply.github.com")

        subprocess.run(
            ["git", "commit", "-m", f"Update insight pages ({now})"],
            cwd=str(tmp_dir), check=True, env=env
        )

        result = subprocess.run(
            ["git", "push", "origin", "main"],
            capture_output=True, text=True, cwd=str(tmp_dir), timeout=60
        )
        if result.returncode != 0:
            print(f"  ERROR: Push failed: {result.stderr[-300:]}")
            return False

        print(f"\n  Deployed to GitHub Pages!")
        print(f"  Live at: {GITHUB_PAGES_URL}")
        return True

    except subprocess.TimeoutExpired:
        print("  ERROR: Operation timed out")
        return False
    except Exception as e:
        print(f"  ERROR: {e}")
        return False
    finally:
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)


def publish_pages(worker_name: str = DEFAULT_WORKER_NAME, dry_run: bool = False,
                  generate_only_mode: bool = False, target: str = "github"):
    """Main orchestrator."""
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Distribution Engine (Layer 3)")
    print(f"  Target: {target}")

    if target == "github":
        return deploy_to_github(dry_run=dry_run)

    # Cloudflare Worker path
    if generate_only_mode:
        generate_only(worker_name)
        print(f"\n  Worker script generated. Deploy manually or via MCP.")
        return True

    if dry_run:
        print(f"  [DRY RUN] Would deploy worker '{worker_name}'")
        pages = prepare_pages()
        total_size = sum(len(v) for v in pages.values())
        print(f"  Pages: {len(pages)} ({total_size / 1024:.1f} KB)")
        print(f"  URL: https://{worker_name}.workers.dev")
        return True

    success = deploy_via_wrangler(worker_name)

    if success:
        print(f"\n  Done. Insights live at https://{worker_name}.workers.dev")
    else:
        print(f"\n  Wrangler deploy failed. Worker script saved for manual/MCP deploy.")
        print(f"  Run with --generate-only to regenerate, then deploy via Cloudflare MCP.")

    return success


def main():
    parser = argparse.ArgumentParser(description="Deploy insight pages to GitHub Pages or Cloudflare Worker")
    parser.add_argument("--target", choices=["github", "cloudflare"], default="github",
                        help="Deployment target (default: github)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be deployed")
    parser.add_argument("--generate-only", action="store_true", help="Generate worker script without deploying")
    parser.add_argument("--name", default=DEFAULT_WORKER_NAME, help=f"Worker name (default: {DEFAULT_WORKER_NAME})")
    args = parser.parse_args()

    success = publish_pages(
        worker_name=args.name,
        dry_run=args.dry_run,
        generate_only_mode=args.generate_only,
        target=args.target,
    )
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
