#!/usr/bin/env python3
"""
Unified Morning Digest — sends a single Telegram message combining
top actionable alerts from ALL 11 scraper sources.

Reads from the existing scraper_dashboard.json (generated by scraper_dashboard.py).
Keeps message under Telegram's 4096 char limit by prioritizing high-value items.

Usage:
    python3 send_morning_digest.py
    python3 send_morning_digest.py --dry-run
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    from dotenv import load_dotenv
    _root = Path(__file__).resolve().parents[4]
    load_dotenv(_root / ".env")
except ImportError:
    pass

try:
    import httpx
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "httpx", "-q"])
    import httpx

ROOT = Path(__file__).resolve().parents[4]
BRIEFINGS_DIR = ROOT / "data" / "briefings"
DASHBOARD_JSON = BRIEFINGS_DIR / "scraper_dashboard.json"


def load_dashboard() -> dict:
    """Load the latest dashboard JSON."""
    if not DASHBOARD_JSON.exists():
        print("  Warning: Dashboard JSON not found. Run scraper_dashboard.py first.")
        return {}
    with open(DASHBOARD_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def build_digest_message(dashboard: dict) -> str:
    """Build a concise, actionable Telegram digest from dashboard data."""
    stats = dashboard.get("stats", {})
    alerts = dashboard.get("alerts", [])
    summary = dashboard.get("summary", {})
    sources = dashboard.get("sources", {})
    today = datetime.now().strftime("%a %d %b")

    lines = [
        f"🌅 <b>Morning Digest — {today}</b>",
        f"📊 {stats.get('active_sources', 0)}/{stats.get('total_sources', 0)} sources | "
        f"{stats.get('total_alerts', 0)} alerts | "
        f"{stats.get('total_data_points', 0):,} data points",
        "",
    ]

    # ── 1. Money Opportunities (highest priority) ──
    money = summary.get("money_opportunities", {})
    if money.get("total", 0) > 0:
        lines.append(f"💰 <b>Money Opportunities</b> — {money['total']} total, {money.get('high_value', 0)} high-value")
        for opp in money.get("top_opportunities", [])[:3]:
            score = opp.get("score", 0)
            emoji = "🔥" if score >= 90 else "⚡"
            title = opp.get("title", "?")[:45]
            url = opp.get("url", "")
            if url:
                lines.append(f"  {emoji} [{score}] <a href=\"{url}\">{title}</a>")
            else:
                lines.append(f"  {emoji} [{score}] {title}")
        lines.append("")

    # ── 2. Job Matches ──
    jobs = summary.get("matched_jobs", {})
    if jobs.get("total", 0) > 0:
        hot = jobs.get("hot", 0)
        lines.append(f"💼 <b>Job Matches</b> — {jobs['total']} matched" + (f", {hot} hot" if hot else ""))
        for j in jobs.get("top_jobs", [])[:3]:
            title = j.get("title", "?")[:40]
            company = j.get("company", "")[:15]
            salary = j.get("salary", "")
            url = j.get("url", "")
            meta = f"{company}" + (f" · {salary}" if salary else "")
            if url:
                lines.append(f"  • <a href=\"{url}\">{title}</a> ({meta})")
            else:
                lines.append(f"  • {title} ({meta})")
        lines.append("")

    # ── 3. Crypto/Stock/DeFi Alerts (financial signals) ──
    financial_alerts = [a for a in alerts if a["source"] in ("Crypto Prices", "Stock Prices", "DeFi Yields")]
    if financial_alerts:
        # Group by source, take top 2 per source
        from collections import defaultdict
        by_source = defaultdict(list)
        for a in financial_alerts:
            by_source[a["source"]].append(a)

        for src_name, src_alerts in by_source.items():
            icon = src_alerts[0].get("icon", "📊") if src_alerts else "📊"
            lines.append(f"{icon} <b>{src_name}</b> — {len(src_alerts)} alerts")
            for a in src_alerts[:2]:
                lines.append(f"  {a['direction']} {a['label']}")
            if len(src_alerts) > 2:
                lines.append(f"  ... +{len(src_alerts) - 2} more")
            lines.append("")

    # ── 4. Exchange Rates (if notable) ──
    fx_alerts = [a for a in alerts if a["source"] == "Exchange Rates"]
    if fx_alerts:
        lines.append(f"💱 <b>Exchange Rates</b> — {len(fx_alerts)} moves")
        for a in fx_alerts[:2]:
            lines.append(f"  {a['direction']} {a['label']}")
        lines.append("")

    # ── 5. Source Health (only if something is down) ──
    inactive = [k for k, v in sources.items() if v.get("status") != "active"]
    if inactive:
        lines.append(f"⚠️ <b>Source Health</b> — {len(inactive)} inactive: {', '.join(inactive)}")
        lines.append("")

    # Footer
    lines.append(f"<i>Full dashboard: scraper_dashboard.html</i>")

    return "\n".join(lines)


def send_telegram(message: str) -> bool:
    """Send message via Telegram Bot API."""
    bot_token = os.environ.get("TELEGRAM_TRADING_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    if not bot_token or not chat_id:
        print("  Warning: Telegram credentials not set")
        return False

    # Telegram has a 4096 char limit for messages
    if len(message) > 4000:
        message = message[:3950] + "\n\n... <i>truncated</i>"

    try:
        resp = httpx.post(
            f"https://api.telegram.org/bot{bot_token}/sendMessage",
            json={
                "chat_id": chat_id,
                "text": message,
                "parse_mode": "HTML",
                "disable_web_page_preview": True,
            },
            timeout=10,
        )
        if resp.status_code == 200:
            print(f"  Telegram digest sent successfully ({len(message)} chars)")
            return True
        else:
            print(f"  Warning: Telegram send failed: {resp.status_code} — {resp.text[:200]}")
            return False
    except Exception as e:
        print(f"  Warning: Telegram error: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Send unified morning digest to Telegram")
    parser.add_argument("--dry-run", action="store_true", help="Print message without sending")
    args = parser.parse_args()

    print(f"\n{'='*50}")
    print(f"  Morning Digest Generator")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"{'='*50}\n")

    dashboard = load_dashboard()
    if not dashboard:
        print("  No dashboard data available. Exiting.")
        sys.exit(1)

    message = build_digest_message(dashboard)

    if args.dry_run:
        print("  [DRY RUN] Message preview:")
        print(f"  {'─'*46}")
        # Strip HTML for preview
        import re
        preview = re.sub(r'<[^>]+>', '', message)
        print(preview)
        print(f"  {'─'*46}")
        print(f"  Length: {len(message)} chars")
    else:
        send_telegram(message)

    print(f"\n  Done.\n")


if __name__ == "__main__":
    main()
